Parkwhere05/Models/Carpark.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Parkwhere05.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Carpark
	{
        public Carpark()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.ParkingHistories = new HashSet<ParkingHistory>();
        }

        [Display(Name = "ID")]
        [Key]
        public int id { get; set; }

        [Display(Name = "Carpark Code")]
        public string carparkNo { get; set; }

        [Display(Name = "Address")]
        public string address { get; set; }

        [Display(Name = "Latitude")]
        public double x_coord { get; set; }

        [Display(Name = "Longitude")]
        public double y_coord { get; set; }

        [Display(Name = "Type of Carpark")]
        public string carparkType { get; set; }

        [Display(Name = "Type of Parking")]
        public string typeOfparking { get; set; }

        [Display(Name = "Short Term Parking")]
        public string shortTermparking { get; set; }

        [Display(Name = "Free Parking")]
        public string freeParking { get; set; }

        [Display(Name = "Night Parking")]
        public string nightParking { get; set; }

        [Display(Name = "Park&Ride Scheme")]
        public string parkAndrideScheme { get; set; }

        [Display(Name = "Adhoc Parking")]
        public string adhocParking { get; set; }

        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<ParkingHistory> ParkingHistories { get; set; }
    }
}

Parkwhere05/Controllers/CarparksController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Parkwhere05.DAL;
using Parkwhere05.Models;

namespace Parkwhere05.Controllers
{
    public class CarparksController : GeneralController<Carpark>
    {
        //To store top five bookmarked carparks
        IEnumerable<Carpark> TopFiveCarparks;

        public CarparksController() {
            dataGateway = new CarparkGateway();
            TopFiveCarparks = ((CarparkGateway)dataGateway).GetTopFiveBookmarks();
        }

        [HttpPost]
        public ActionResult Index(string value1, string value2)
        {
            if (Session["searchResult"] == null)
            {
                ViewBag.List = ((CarparkGateway)dataGateway).FilterByType(value1, value2);
                return View(TopFiveCarparks);
            }
            else {
                string searchResult = Session["searchResult"].ToString();
                ViewBag.List = ((CarparkGateway)dataGateway).FilterAddressByType(searchResult, value1, value2);
                return View(TopFiveCarparks);
            }
        }

        [HttpGet]
        public ActionResult Index(string addResults)
        {
            Session["searchResult"] = addResults;
            ViewBag.List = ((CarparkGateway)dataGateway).searchCarpark(addResults);
            return View(TopFiveCarparks);
        }

        public override ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carpark obj = dataGateway.SelectById(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            List<string[]> CarparkList;
            CarparkList = new List<string[]>();
            string[] listString = new string[2];
            listString[0] = obj.x_coord.ToString();
            listString[1] = obj.y_coord.ToString();
            CarparkList.Add(listString);
            ViewBag.Corr = CarparkList;
            ViewBag.CurrentCor = HomeController.CurrentCorrList;

            Carpark carpark = dataGateway.SelectById(id);
            return View(carpark);
        }
    }
}

Parkwhere05/Views/Carparks/Details.cshtml
@model Parkwhere05.Models.Carpark

@{
    ViewBag.Title = "Details";
}
<div id="wellHomePage">
    <br />

    <h2>Details</h2>

    <div>
        <h4>Carpark</h4>
        
        @Html.ActionLink("Bookmark this carpark!", "../Bookmarks/Create", new { carparkId = Model.id, address = Model.address })
        @Html.ActionLink("Save this carpark!", "../ParkingHistories/Create", new { carparkId = Model.id, address = Model.address })


        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.carparkNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.carparkNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.address)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.x_coord)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.x_coord)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.y_coord)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.y_coord)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.carparkType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.carparkType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.typeOfparking)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.typeOfparking)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.shortTermparking)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.shortTermparking)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.freeParking)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.freeParking)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.nightParking)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nightParking)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.parkAndrideScheme)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.parkAndrideScheme)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.adhocParking)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.adhocParking)
            </dd>

        </dl>
    </div>
    <script>
    function initMap() {

        var directionsDisplay = new google.maps.DirectionsRenderer;
        var directionsService = new google.maps.DirectionsService;
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: { lat: 1.292582, lng: 103.855444 }
        });
        directionsDisplay.setMap(map);

        calculateAndDisplayRoute(directionsService, directionsDisplay);
        document.getElementById('mode').addEventListener('change', function () {
            calculateAndDisplayRoute(directionsService, directionsDisplay);
        });
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var locations = @Html.Raw(Json.Encode(ViewBag.Corr));
        var currentlocations = @Html.Raw(Json.Encode(ViewBag.CurrentCor));
        var lat =parseFloat(locations[0][0]);
        var lng =parseFloat(locations[0][1]);
        var currlat =parseFloat(currentlocations[0][0]);
        var currlng =parseFloat(currentlocations[0][1]);
        var selectedMode = document.getElementById('mode').value;
        directionsService.route({
            origin: { lat: currlat, lng: currlng },  // current lat lng
            destination: { lat: lat , lng: lng},//dest
            // Note that Javascript allows us to access the constant
            // using square brackets and a string value as its
            // "property."
            travelMode: google.maps.TravelMode[selectedMode]
        }, function (response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
            } else {
                window.alert('Directions request failed due to ' + status);
            }
        });
    }

    window.onload = initMap;
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initMap"
            async defer></script>

    <div>
        <div id="floating-panel">
            <b>Mode of Travel: </b>
            <select id="mode">
                <option value="DRIVING">Driving</option>
                <option value="WALKING">Walking</option>
                <option value="BICYCLING">Bicycling</option>
                <option value="TRANSIT">Transit</option>
            </select>
        </div>
        <div>
            <div id="map" style="height: 450px;"></div>
        </div>
    </div>

    
    
  

    <p>
        @*@Html.ActionLink("Edit", "Edit", new { id = Model.id }) |*@
        @Html.ActionLink("Back to List", "Index")
    </p>

</div>

Parkwhere05/Views/Carparks/Index.cshtml
@model IEnumerable<Parkwhere05.Models.Carpark>

@{
    ViewBag.Title = "Index";
    
}
@Styles.Render("~/Content/css")

<div class="well" id="wellHomePage">
    <h2>Search</h2>
    <p>@ViewBag.Lat</p>
    <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
    <script src="~/Scripts/svy21.js" type="text/javascript"></script>

    @section scripts {

        <section class="scripts">
            <script type="text/javascript">
        var map = new google.maps.Map(document.getElementById('map_canvas'), {
            zoom: 11,
            center: new google.maps.LatLng(1.3485232,103.8208814),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        var infowindow = new google.maps.InfoWindow();
        var marker, i;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                var marker = new google.maps.Marker({
                    position: pos,
                    map: map,
                    title: 'Your current location!',
                    icon: 'https://cdn0.iconfinder.com/data/icons/huge-business-icons/40/Car.png'
                });
                map.setCenter(pos);
            }, function() {
                handleLocationError(true, infoWindow, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map.getCenter());
        }

        var locations = @Html.Raw(Json.Encode(ViewBag.List));

            if(locations!=null)
            {
                for (i = 0; i < locations.length; i++) {

                    // Initialization
                    var cv = new SVY21();

                    var resultLatLon = cv.computeLatLon(locations[i][5], locations[i][6]);
                    console.log(resultLatLon);

                    marker = new google.maps.Marker({
                        position: new google.maps.LatLng(resultLatLon.lat, resultLatLon.lon),
                        map: map
                    });

                    google.maps.event.addListener(marker, 'click', (function(marker, i) {
                        return function() {
                            infowindow.setContent("Carpark Address :<br />" + locations[i][2] + "<br />" + '<a href="/Carparks/Details/' + locations[i][0] + '">Carpark Details</a>');
                            infowindow.open(map, marker);
                        }
                    })(marker, i));
                }
            }
            </script>
        </section>
    }


    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript">
        google.maps.event.addDomListener(window, 'load', function () {
            var places = new google.maps.places.Autocomplete(document.getElementById('txtPlaces'));
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                var address = place.formatted_address;
                var latitude = place.geometry.location.lat();
                var longitude = place.geometry.location.lng();
                var mesg = "Address: " + address;
                mesg += "\nLatitude: " + latitude;
                mesg += "\nLongitude: " + longitude;
                document.getElementById("addResults").value = address;
            });
        });
    </script>
    <span>Location:</span>
    @using (Html.BeginForm("Index", "Carparks", FormMethod.Get))
    {
        <input type="text" id="txtPlaces" style="width: 250px" placeholder="Enter a location" />
        <input type="hidden" name="addResults" id="addResults" style="width: 250px" />
        <input type="submit" value="Search" />
    }

    @using (Html.BeginForm("Index", "Carparks", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <strong>Type of Parking</strong>
        <div class="form-group">
            <select class="form-control" name="value1">
                <option>
                    ELECTRONIC PARKING
                </option>
                <option>
                    COUPON PARKING
                </option>
            </select>
        </div>
        <strong>CarPark Type</strong>
        <div class="form-group">
            <select class="form-control" name="value2">
                <option>
                    SURFACE CAR PARK
                </option>
                <option>
                    MULTI-STOREY CAR PARK
                </option>
            </select>
        </div>
        <button type="submit" class="btn btn-default">
            Submit
        </button>

    }

   
    <div>
        <div id="map_canvas" style="height: 450px;"></div>
    </div>

<br />
    <div>
        <h3>TOP 5 MOST FREQUENTLY BOOKMARK CARPARK</h3>
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.carparkNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.carparkNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.id })
            </td>
        </tr>
        }

    </table>


</div>
