Parkwhere05/Models/PetrolStation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Parkwhere05.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class PetrolStation
    {
        [Display(Name = "ID")]
        [Key]
        public int Id { get; set; }

        [Display(Name = "Station Name")]
        public string petrolStationName { get; set; }

        [Display(Name = "Address")]
        public string address { get; set; }

        [Display(Name = "Latitude")]
        public Nullable<double> latitude { get; set; }

        [Display(Name = "Longitude")]
        public Nullable<double> longitude { get; set; }
    }
}

Parkwhere05/Controllers/PetrolStationsController.cs
using System.Web.Mvc;
using Parkwhere05.DAL;
using Parkwhere05.Models;
using System.Net;
using System.Collections.Generic;

namespace Parkwhere05.Controllers
{
    public class PetrolStationsController : GeneralController<PetrolStation>
    {
        public PetrolStationsController()
        {
            dataGateway = new PetrolStationGateway();
        }

        public override ActionResult Index(int? id)
        {
            ViewBag.List = ((PetrolStationGateway)dataGateway).GetAllPetrolStation();
            return View();
        }

        [HttpPost]
        public ActionResult Index(string addResults)
        {
            ViewBag.List = ((PetrolStationGateway)dataGateway).searchPetrolStation(addResults);
            return View();
        }

        public override ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PetrolStation obj = dataGateway.SelectById(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            List<string[]> PetrolStationList;
            PetrolStationList = new List<string[]>();
            string[] listString = new string[2];
            listString[0] = obj.latitude.ToString();
            listString[1] = obj.longitude.ToString();
            PetrolStationList.Add(listString);
            ViewBag.Corr = PetrolStationList;
            ViewBag.CurrentCor = HomeController.CurrentCorrList;
            return View();
        }

    }
}

Parkwhere05/Views/PetrolStations/Details.cshtml
@model Parkwhere05.Models.PetrolStation


@{
    ViewBag.Title = "Details";

}
<div class="well" id="wellHomePage">
    <br/>

    <h2>Petrol Station Details</h2>

    <br/>

    <script>
        function initMap() {

            var directionsDisplay = new google.maps.DirectionsRenderer;
            var directionsService = new google.maps.DirectionsService;
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 14,
                center: { lat: 1.292582, lng: 103.855444 }
            });
            directionsDisplay.setMap(map);

            calculateAndDisplayRoute(directionsService, directionsDisplay);
            document.getElementById('mode').addEventListener('change', function () {
                calculateAndDisplayRoute(directionsService, directionsDisplay);
            });
        }

        function calculateAndDisplayRoute(directionsService, directionsDisplay) {
            var locations = @Html.Raw(Json.Encode(ViewBag.Corr));
            var currentlocations = @Html.Raw(Json.Encode(ViewBag.CurrentCor));
            var lat =parseFloat(locations[0][0]);
            var lng =parseFloat(locations[0][1]);
            var currlat =parseFloat(currentlocations[0][0]);
            var currlng =parseFloat(currentlocations[0][1]);
            var selectedMode = document.getElementById('mode').value;
            directionsService.route({
                origin: { lat: currlat, lng: currlng },  // current lat lng
                destination: { lat: lat , lng: lng},//dest
                // Note that Javascript allows us to access the constant
                // using square brackets and a string value as its
                // "property."
                travelMode: google.maps.TravelMode[selectedMode]
            }, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                } else {
                    window.alert('Directions request failed due to ' + status);
                }
            });
        }

        window.onload = initMap;
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initMap"
            async defer></script>


    <div id="floating-panel">
        <b>Mode of Travel: </b>
        <select id="mode">
            <option value="DRIVING">Driving</option>
            <option value="WALKING">Walking</option>
            <option value="BICYCLING">Bicycling</option>
            <option value="TRANSIT">Transit</option>
        </select>
    </div>
    <div>
        <div id="map" style="height: 450px;"></div>
    </div>
</div>



<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Parkwhere05/Views/PetrolStations/Index.cshtml
@model IEnumerable<Parkwhere05.Models.PetrolStation>

@{
    ViewBag.Title = "Index";
}
<div class="well" id="wellHomePage">
    <h2>Index</h2>

    <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>


    @section scripts {

        <section class="scripts">
            <script type="text/javascript">
                var map = new google.maps.Map(document.getElementById('map_canvas'), {
                    zoom: 11,
                    center: new google.maps.LatLng(1.3485232,103.8208814),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });


                // Try HTML5 geolocation.
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        var pos = {
                            lat: position.coords.latitude,
                            lng: position.coords.longitude
                        };

                        var marker = new google.maps.Marker({
                            position: pos,
                            map: map,
                            title: 'Your current location!',
                            icon: 'https://cdn0.iconfinder.com/data/icons/huge-business-icons/40/Car.png'
                        });
                        map.setCenter(pos);
                    }, function() {
                        handleLocationError(true, infoWindow, map.getCenter());
                    });
                } else {
                    // Browser doesn't support Geolocation
                    handleLocationError(false, infoWindow, map.getCenter());
                }

                var infowindow = new google.maps.InfoWindow();
                var marker, i;
                var locations = @Html.Raw(Json.Encode(ViewBag.List));

                if(locations!=null)
                {
                    for (i = 0; i < locations.length; i++) {
                        marker = new google.maps.Marker({
                            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                            map: map
                        });
                        google.maps.event.addListener(marker, 'click', (function(marker, i) {
                            return function() {
                                infowindow.setContent("PetrolStation Name :<br />" + locations[i][0] + "<br />" + '<a href="/PetrolStations/Details/' + locations[i][3] + '">Click here for Details</a>');
                                infowindow.open(map, marker);
                            }
                        })(marker, i));
                    }
                }
            </script>
        </section>
    }
    @*autocomplete scripts*@

    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript">
        google.maps.event.addDomListener(window, 'load', function () {
            var places = new google.maps.places.Autocomplete(document.getElementById('txtPlaces'));
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                var address = place.formatted_address;
                var latitude = place.geometry.location.lat();
                var longitude = place.geometry.location.lng();
                var mesg = "Address: " + address;
                mesg += "\nLatitude: " + latitude;
                mesg += "\nLongitude: " + longitude;
                document.getElementById("addResults").value = address;
            });
        });
    </script>




    <span>Location:</span>
    @using (Html.BeginForm("Index", "PetrolStations", FormMethod.Post))
    {
        <input type="text" id="txtPlaces" style="width: 250px" placeholder="Enter a location" />
        <input type="hidden" name="addResults" id="addResults" style="width: 250px" />
        <input type="submit" value="Search" />
    }
    <div>
        <div id="map_canvas" style="height: 450px;"></div>
    </div>
</div>